/** Workbook preparation only for “ACM PSU — Club Records”.
 * Supabase Edge Functions own every data write. This script creates and formats
 * canonical mirror tabs; it never reads Supabase or accepts registrations. */
var CANONICAL_SHEETS = {
  'People': ['Name','PSU Email','Person Type','University Role','ACM Role','Project Roles','Account State','Admin/System Roles','Student ID','Major','Academic Year','Membership Status'],
  'Members': ['Name','PSU Email','Student ID','Major','Academic Year','Membership Status','Membership Start','Membership End','Member Number','Chapter Year','Club Position','Account State'],
  'Club Positions': ['Position ID','Slug','Position Name','Category','Rank','Active','Holder Name','Holder Email','University Role','Assignment Start','Assignment End','Chapter Year','Assignment Status'],
  'Opportunity Positions': ['Opportunity ID','Project','Project Kind','Project Status','Position','Description','Openings','Approved','Pending','Remaining','Open','Closes On','Created At'],
  'Position Applications': ['Application ID','Applicant Name','Email','University Role','Project','Position','Availability','Note','Status','Admin Note','Decided By','Decided At','Applied At'],
  'Event Participation': ['Participation ID','Person Name','Email','University Role','Project','Project Kind','Opportunity Position','Role','Status','Started','Ended','Verified At','Verified By','Updated At'],
  'Contributions': ['Contribution ID','Person Name','Email','University Role','Project','Title','Type','Role','Description','Occurred On','Status','Verified At','Reviewed By','Review Note','Created At'],
  'Inquiries': ['Reference','Received','From','Email','Category','Subject','Message','Status','Assigned To','Responded At','Response Delivered','Closed At'],
  'University Export Log': ['Generated At','Dataset','Format','Rows','Generated By','Destination']
};

function setupClubRecordsWorkbook() {
  var book = SpreadsheetApp.getActive();
  if (!book) throw new Error('Open this script from the ACM PSU — Club Records workbook.');
  Object.keys(CANONICAL_SHEETS).forEach(function (name) {
    var headers = CANONICAL_SHEETS[name];
    var sheet = book.getSheetByName(name) || book.insertSheet(name);
    // Safe to rerun: never clear data rows or touch legacy tabs.
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
    sheet.setFrozenRows(1);
    sheet.getRange(1, 1, 1, headers.length).setBackground('#142033').setFontColor('#ffffff').setFontWeight('bold');
    if (sheet.getFilter()) sheet.getFilter().remove();
    sheet.getRange(1, 1, Math.max(sheet.getLastRow(), 2), headers.length).createFilter();
    sheet.autoResizeColumns(1, headers.length);
  });
  SpreadsheetApp.getUi().alert('Canonical tabs are ready. Legacy tabs were not renamed or deleted. Use the portal’s “Update Google Sheet” action to load Supabase data.');
}

/** Retired web-app endpoints remain harmless until their deployments are archived. */
function doPost() { return json_({status:'error',message:'Registration writes moved to the ACM PSU Supabase portal.'}); }
function doGet() { return json_({status:'retired',message:'This Apps Script only prepares workbook formatting.'}); }
function json_(payload) { return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON); }
