/**
 * ACM PSU — Club Records Workbook Setup
 *
 * PURPOSE
 * -------
 * Prepares and formats the administrative Google Sheets workbook used by the
 * ACM PSU platform.
 *
 * Supabase remains the canonical system of record for the platform.
 *
 * This script:
 * - creates missing workbook tabs;
 * - applies headers and formatting;
 * - protects externally managed event-registration tabs from accidental edits;
 * - never reads data from Supabase;
 * - never accepts public registration submissions;
 * - never clears registration rows.
 *
 * TWO DIFFERENT GROUPS OF TABS
 * ----------------------------
 *
 * CANONICAL_SHEETS
 *   Supabase-owned snapshot mirrors.
 *
 *   These worksheets are refreshed by the `club-records-sheet-sync`
 *   Supabase Edge Function. Supabase is authoritative and the worksheets are
 *   administrative copies of platform data.
 *
 * EVENT_SHEETS
 *   Externally managed event-registration worksheets.
 *
 *   Current event tabs:
 *   - jam26
 *   - ctf30
 *
 *   They are populated by the event registration integrations and are
 *   deliberately excluded from the normal Supabase snapshot sync.
 *
 *   This setup script never rewrites an existing event header or registration
 *   data. It may seed row 1 only when an event worksheet is empty.
 */


/* ==========================================================================
   CONFIGURATION
   ========================================================================== */


/**
 * Supabase-owned workbook mirrors.
 *
 * These headers should match the current output of the ACM PSU platform's
 * Google Sheets synchronization system.
 */
var CANONICAL_SHEETS = {
  'People': [
    'Name',
    'PSU Email',
    'Person Type',
    'University Role',
    'ACM Role',
    'Project Roles',
    'Account State',
    'Admin/System Roles',
    'Student ID',
    'Major',
    'Academic Year',
    'Membership Status'
  ],

  'Members': [
    'Name',
    'PSU Email',
    'Student ID',
    'Major',
    'Academic Year',
    'Membership Status',
    'Membership Start',
    'Membership End',
    'Member Number',
    'Chapter Year',
    'Club Position',
    'Account State'
  ],

  'Club Positions': [
    'Position ID',
    'Slug',
    'Position Name',
    'Category',
    'Rank',
    'Active',
    'Holder Name',
    'Holder Email',
    'University Role',
    'Assignment Start',
    'Assignment End',
    'Chapter Year',
    'Assignment Status'
  ],

  'Opportunity Positions': [
    'Opportunity ID',
    'Project',
    'Project Kind',
    'Project Status',
    'Position',
    'Description',
    'Openings',
    'Approved',
    'Pending',
    'Remaining',
    'Open',
    'Closes On',
    'Created At'
  ],

  'Position Applications': [
    'Application ID',
    'Applicant Name',
    'Email',
    'University Role',
    'Project',
    'Position',
    'Availability',
    'Note',
    'Status',
    'Admin Note',
    'Decided By',
    'Decided At',
    'Applied At'
  ],

  'Event Participation': [
    'Participation ID',
    'Person Name',
    'Email',
    'University Role',
    'Project',
    'Project Kind',
    'Opportunity Position',
    'Role',
    'Status',
    'Started',
    'Ended',
    'Verified At',
    'Verified By',
    'Updated At'
  ],

  'Contributions': [
    'Contribution ID',
    'Person Name',
    'Email',
    'University Role',
    'Project',
    'Title',
    'Type',
    'Role',
    'Description',
    'Occurred On',
    'Status',
    'Verified At',
    'Reviewed By',
    'Review Note',
    'Created At'
  ],

  'Inquiries': [
    'Reference',
    'Received',
    'From',
    'Email',
    'Category',
    'Subject',
    'Message',
    'Status',
    'Assigned To',
    'Responded At',
    'Response Delivered',
    'Closed At'
  ],

  'University Export Log': [
    'Generated At',
    'Dataset',
    'Format',
    'Rows',
    'Generated By',
    'Destination'
  ]
};


/**
 * Event-registration worksheets.
 *
 * IMPORTANT
 * ---------
 * These tabs are NOT Supabase snapshot mirrors.
 *
 * Existing event headers are treated as externally owned. If the configured
 * headers below differ from the live worksheet, this script reports the
 * mismatch and changes nothing.
 *
 * Row shape:
 *
 * jam26
 *   One row per TEAM SUBMISSION.
 *
 *   The personal fields identify the participant submitting the registration.
 *   Team Name and Team Members describe the registered team.
 *
 * ctf30
 *   One row per TEAM.
 *
 *   The captain has the primary contact phone number.
 *   Members 2 and 3 have:
 *   - Name
 *   - University ID
 *   - University Email
 *   - Major
 */
var EVENT_SHEETS = {
  // ACM Programming Jam 2026 — one row per team submission.
  'jam26': [
    'Timestamp',
    'Full Name',
    'University ID',
    'University Email',
    'Phone Number',
    'Major',
    'Team Name',
    'Team Members'
  ],

  // ACM/CyberTech CTF 3.0 — one row per team.
  'ctf30': [
    'Timestamp',
    'Team Name',

    'Captain Name',
    'Captain University ID',
    'Captain University Email',
    'Captain Phone Number',
    'Captain Major',

    'Member 2 Name',
    'Member 2 University ID',
    'Member 2 University Email',
    'Member 2 Major',

    'Member 3 Name',
    'Member 3 University ID',
    'Member 3 University Email',
    'Member 3 Major',

    'Experience Level'
  ]
};


var HEADER_BACKGROUND = '#142033';
var EVENT_HEADER_BACKGROUND = '#1d3a2f';
var HEADER_FONT_COLOR = '#ffffff';


/* ==========================================================================
   MAIN SETUP
   ========================================================================== */


/**
 * Main workbook setup function.
 *
 * Run this from:
 *
 * ACM Records → Prepare workbook tabs
 *
 * or manually from the Apps Script editor.
 */
function setupClubRecordsWorkbook() {
  var book = SpreadsheetApp.getActiveSpreadsheet();

  if (!book) {
    throw new Error(
      'Open this script from the ACM PSU — Club Records workbook.'
    );
  }

  /*
   * Fail before touching anything if a worksheet has accidentally been placed
   * in both configuration groups.
   */
  assertNoSheetGroupOverlap_();

  var notes = [];

  /*
   * Prepare Supabase-owned mirror tabs.
   */
  Object.keys(CANONICAL_SHEETS).forEach(function (name) {
    prepareCanonicalSheet_(
      book,
      name,
      CANONICAL_SHEETS[name],
      notes
    );
  });

  /*
   * Prepare externally managed event-registration tabs.
   */
  Object.keys(EVENT_SHEETS).forEach(function (name) {
    prepareEventSheet_(
      book,
      name,
      EVENT_SHEETS[name],
      notes
    );
  });

  SpreadsheetApp.flush();

  report_(notes);
}


/* ==========================================================================
   SAFETY GUARDS
   ========================================================================== */


/**
 * Event-registration tabs must never become Supabase mirror tabs.
 *
 * If an event worksheet were accidentally added to CANONICAL_SHEETS, the
 * normal Supabase workbook synchronization could clear and rebuild it.
 *
 * Stop immediately instead.
 */
function assertNoSheetGroupOverlap_() {
  Object.keys(EVENT_SHEETS).forEach(function (name) {
    if (CANONICAL_SHEETS.hasOwnProperty(name)) {
      throw new Error(
        'Configuration error: "' +
          name +
          '" is listed in both CANONICAL_SHEETS and EVENT_SHEETS. ' +
          'Event-registration tabs must never be targeted by the normal ' +
          'Supabase snapshot synchronization.'
      );
    }
  });
}


/* ==========================================================================
   CANONICAL SUPABASE MIRROR TABS
   ========================================================================== */


/**
 * Prepares a Supabase-owned mirror worksheet.
 *
 * Row 1 is controlled by the current platform schema.
 *
 * This setup function does NOT clear existing data rows. The actual Edge
 * Function remains responsible for refreshing snapshot data.
 */
function prepareCanonicalSheet_(book, name, headers, notes) {
  var sheet = book.getSheetByName(name);

  if (!sheet) {
    sheet = book.insertSheet(name);
  }

  ensureEnoughColumns_(sheet, headers.length);

  sheet
    .getRange(1, 1, 1, headers.length)
    .setValues([headers]);

  styleHeader_(
    sheet,
    headers.length,
    HEADER_BACKGROUND
  );

  formatColumns_(sheet, headers);

  applyFilter_(
    sheet,
    headers.length
  );

  notes.push(
    'Mirror  ' +
      name +
      ' — headers applied (' +
      headers.length +
      ' columns).'
  );
}


/* ==========================================================================
   EVENT REGISTRATION TABS
   ========================================================================== */


/**
 * Prepares an externally managed event-registration worksheet.
 *
 * SAFE BEHAVIOR
 * -------------
 *
 * Missing tab:
 *   Creates it and seeds configured headers.
 *
 * Existing but empty tab:
 *   Seeds configured headers.
 *
 * Existing tab with matching headers:
 *   Leaves row 1 untouched.
 *
 * Existing tab with DIFFERENT headers:
 *   Writes nothing and reports a HEADER MISMATCH.
 *
 * Registration rows are never cleared or rewritten here.
 */
function prepareEventSheet_(book, name, headers, notes) {
  var configured =
    headers && headers.length
      ? headers
      : null;

  var sheet = book.getSheetByName(name);
  var created = false;

  if (!sheet) {
    sheet = book.insertSheet(name);
    created = true;
  }

  var existing = readHeaderRow_(sheet);

  /*
   * Empty worksheet + configured schema:
   * safe to seed row 1.
   */
  if (configured && !existing.length) {
    ensureEnoughColumns_(
      sheet,
      configured.length
    );

    sheet
      .getRange(
        1,
        1,
        1,
        configured.length
      )
      .setValues([configured]);

    existing = configured.slice();

    notes.push(
      'Event   ' +
        name +
        ' — ' +
        (created ? 'created' : 'was empty') +
        ', header row seeded (' +
        configured.length +
        ' columns).'
    );
  }

  /*
   * Existing worksheet disagrees with configuration:
   * live worksheet wins.
   */
  else if (
    configured &&
    !sameHeaders_(configured, existing)
  ) {
    notes.push(
      'Event   ' +
        name +
        ' — HEADER MISMATCH, nothing written.\n' +
        '          in sheet: ' +
        existing.join(' | ') +
        '\n' +
        '          in script: ' +
        configured.join(' | ') +
        '\n' +
        '          Update EVENT_SHEETS in Code.gs to match the live sheet.'
    );
  }

  /*
   * Correct existing event header.
   */
  else if (configured) {
    notes.push(
      'Event   ' +
        name +
        ' — header row matches, left untouched.'
    );
  }

  /*
   * No configured schema but an existing header exists.
   */
  else if (existing.length) {
    notes.push(
      'Event   ' +
        name +
        ' — no header configured; existing row 1 left untouched.'
    );
  }

  /*
   * Brand-new empty tab with no configured schema.
   */
  else {
    notes.push(
      'Event   ' +
        name +
        ' — ' +
        (created ? 'created, ' : '') +
        'empty and no header configured.'
    );
  }

  /*
   * Styling is allowed because it does not change registration values.
   */
  var width =
    existing.length ||
    sheet.getLastColumn();

  if (width > 0) {
    styleHeader_(
      sheet,
      width,
      EVENT_HEADER_BACKGROUND
    );

    applyFilter_(
      sheet,
      width
    );

    formatColumns_(
      sheet,
      existing.length
        ? existing
        : headers
    );
  }

  /*
   * Warn humans before editing an event-registration worksheet.
   *
   * This is intentionally warning-only, not a hard lock.
   */
  protectEventSheet_(
    sheet,
    name
  );
}


/* ==========================================================================
   EVENT SHEET PROTECTION
   ========================================================================== */


/**
 * Applies warning-only protection to an event-registration worksheet.
 *
 * Why warning-only?
 *
 * It warns a human editing through Google Sheets while still allowing
 * programmatic integrations to write.
 *
 * The registration writer identity is intentionally not assumed here.
 */
function protectEventSheet_(sheet, name) {
  var description =
    'ACM event registrations (' +
    name +
    ') — externally managed. ' +
    'Excluded from the Supabase snapshot sync. ' +
    'Do not sort, clear, or paste over registration data.';

  var protections =
    sheet.getProtections(
      SpreadsheetApp.ProtectionType.SHEET
    );

  var protection;

  if (protections && protections.length) {
    protection = protections[0];
  } else {
    protection = sheet.protect();
  }

  protection.setDescription(description);
  protection.setWarningOnly(true);
}


/* ==========================================================================
   HEADER UTILITIES
   ========================================================================== */


/**
 * Reads row 1 as a normalized list of header names.
 */
function readHeaderRow_(sheet) {
  var width = sheet.getLastColumn();

  if (
    width < 1 ||
    sheet.getLastRow() < 1
  ) {
    return [];
  }

  var row = sheet
    .getRange(
      1,
      1,
      1,
      width
    )
    .getValues()[0];

  /*
   * Remove trailing blank header cells without collapsing valid columns in
   * the middle of a header row.
   */
  while (
    row.length &&
    String(row[row.length - 1]).trim() === ''
  ) {
    row.pop();
  }

  return row.map(function (cell) {
    return String(cell).trim();
  });
}


/**
 * Exact normalized header comparison.
 */
function sameHeaders_(a, b) {
  if (a.length !== b.length) {
    return false;
  }

  for (
    var i = 0;
    i < a.length;
    i += 1
  ) {
    if (
      String(a[i]).trim() !==
      String(b[i]).trim()
    ) {
      return false;
    }
  }

  return true;
}


/* ==========================================================================
   FORMATTING
   ========================================================================== */


/**
 * Ensures enough worksheet columns exist.
 */
function ensureEnoughColumns_(sheet, requiredColumns) {
  var currentColumns =
    sheet.getMaxColumns();

  if (
    currentColumns <
    requiredColumns
  ) {
    sheet.insertColumnsAfter(
      currentColumns,
      requiredColumns -
        currentColumns
    );
  }
}


/**
 * Applies the standard header appearance.
 */
function styleHeader_(sheet, width, background) {
  if (width < 1) {
    return;
  }

  sheet.setFrozenRows(1);

  sheet
    .getRange(
      1,
      1,
      1,
      width
    )
    .setBackground(background)
    .setFontColor(
      HEADER_FONT_COLOR
    )
    .setFontWeight('bold')
    .setHorizontalAlignment('center')
    .setVerticalAlignment('middle')
    .setWrap(true);

  sheet.setRowHeight(
    1,
    42
  );
}


/**
 * Applies column sizing and data formatting.
 */
function formatColumns_(sheet, headers) {
  if (
    !headers ||
    !headers.length
  ) {
    return;
  }

  var maxRows =
    sheet.getMaxRows();

  headers.forEach(
    function (header, index) {
      var column =
        index + 1;

      sheet.setColumnWidth(
        column,
        columnWidthFor_(header)
      );

      /*
       * Do not needlessly format an empty worksheet below row 1.
       */
      if (maxRows <= 1) {
        return;
      }

      var dataRange =
        sheet.getRange(
          2,
          column,
          maxRows - 1,
          1
        );

      dataRange
        .setVerticalAlignment(
          'middle'
        );

      if (
        isLongTextColumn_(header)
      ) {
        dataRange
          .setWrap(true)
          .setVerticalAlignment(
            'top'
          );
      } else {
        dataRange.setWrap(false);
      }

      if (
        isDateTimeColumn_(header)
      ) {
        dataRange.setNumberFormat(
          'yyyy-mm-dd hh:mm'
        );
      }

      if (
        isDateOnlyColumn_(header)
      ) {
        dataRange.setNumberFormat(
          'yyyy-mm-dd'
        );
      }
    }
  );
}


/**
 * Recreates a basic filter for the visible table.
 */
function applyFilter_(sheet, width) {
  if (width < 1) {
    return;
  }

  var existingFilter =
    sheet.getFilter();

  if (existingFilter) {
    existingFilter.remove();
  }

  /*
   * Only create the filter when there is at least one actual data row.
   *
   * Header-only filters can conflict with an existing Google Sheets table or
   * overlapping filter range. The frozen/styled header remains enough until
   * data exists.
   */
  if (sheet.getLastRow() <= 1) {
    return;
  }

  sheet
    .getRange(
      1,
      1,
      sheet.getLastRow(),
      width
    )
    .createFilter();
}


/**
 * Appropriate display width for a column.
 */
function columnWidthFor_(header) {
  var text =
    String(header || '');

  if (
    text.includes('Message') ||
    text.includes('Response') ||
    text.includes('Contribution') ||
    text.includes('Description') ||
    text.includes('Admin Note') ||
    text.includes('Review Note') ||
    text === 'Note' ||
    text === 'Team Members'
  ) {
    return 320;
  }

  if (
    text.includes('Email') ||
    text.includes('Project') ||
    text.includes('Event')
  ) {
    return 230;
  }

  if (
    text.includes('Name') ||
    text.includes('Current Holder')
  ) {
    return 210;
  }

  if (
    text.includes('Availability')
  ) {
    return 220;
  }

  if (
    isDateTimeColumn_(text) ||
    isDateOnlyColumn_(text)
  ) {
    return 175;
  }

  if (
    text.includes('ID')
  ) {
    return 190;
  }

  if (
    text.includes('Status')
  ) {
    return 160;
  }

  if (
    text.includes('Major')
  ) {
    return 190;
  }

  if (
    text.includes('Phone')
  ) {
    return 170;
  }

  return 150;
}


/**
 * Long-text fields should wrap.
 */
function isLongTextColumn_(header) {
  var text =
    String(header || '');

  return (
    text.includes('Message') ||
    text.includes('Response') ||
    text.includes('Contribution') ||
    text.includes('Description') ||
    text.includes('Availability') ||
    text.includes('Admin Note') ||
    text.includes('Review Note') ||
    text === 'Note' ||
    text === 'Team Members'
  );
}


/**
 * Timestamp/date-time fields.
 */
function isDateTimeColumn_(header) {
  var text =
    String(header || '');

  return (
    text === 'Timestamp' ||
    text === 'Received' ||
    text === 'Generated At' ||
    text === 'Created At' ||
    text === 'Updated At' ||
    text === 'Applied At' ||
    text === 'Decided At' ||
    text === 'Verified At' ||
    text === 'Responded At' ||
    text === 'Closed At' ||
    text.endsWith(' At')
  );
}


/**
 * Date-only fields.
 */
function isDateOnlyColumn_(header) {
  var text =
    String(header || '');

  return (
    text === 'Membership Start' ||
    text === 'Membership End' ||
    text === 'Assignment Start' ||
    text === 'Assignment End' ||
    text === 'Started' ||
    text === 'Ended' ||
    text === 'Occurred On' ||
    text === 'Closes On'
  );
}


/* ==========================================================================
   REPORTING
   ========================================================================== */


/**
 * Displays the setup report.
 *
 * Works when called from the spreadsheet UI or directly from the Apps Script
 * editor.
 */
function report_(notes) {
  var message =
    notes.join('\n') +
    '\n\n' +
    'Canonical mirror tabs are refreshed from Supabase through the ACM ' +
    'platform Google Sheet synchronization. Event-registration tabs are ' +
    'externally managed and are excluded from that snapshot sync.';

  Logger.log(message);

  try {
    SpreadsheetApp
      .getUi()
      .alert(message);
  } catch (err) {
    /*
     * No spreadsheet UI is available when execution is initiated in certain
     * trigger/editor contexts. Logger output above remains available.
     */
  }
}


/* ==========================================================================
   WORKBOOK MENU
   ========================================================================== */


/**
 * Adds the workbook maintenance menu whenever the spreadsheet is opened.
 */
function onOpen() {
  try {
    SpreadsheetApp
      .getUi()
      .createMenu('ACM Records')
      .addItem(
        'Prepare workbook tabs',
        'setupClubRecordsWorkbook'
      )
      .addToUi();
  } catch (err) {
    /*
     * Container UI unavailable.
     * setupClubRecordsWorkbook() remains runnable manually.
     */
  }
}


/* ==========================================================================
   RETIRED WEB ENDPOINTS
   ========================================================================== */


/**
 * This central workbook script is NOT a public registration API.
 *
 * Historical Apps Script registration endpoints remain explicitly retired.
 */
function doPost() {
  return json_({
    status: 'error',
    message:
      'This ACM Club Records Apps Script does not accept public writes.'
  });
}


/**
 * GET requests only report the retired state.
 */
function doGet() {
  return json_({
    status: 'retired',
    message:
      'This Apps Script only prepares the ACM PSU Club Records workbook.'
  });
}


/**
 * JSON response helper for retired endpoints.
 */
function json_(payload) {
  return ContentService
    .createTextOutput(
      JSON.stringify(payload)
    )
    .setMimeType(
      ContentService.MimeType.JSON
    );
}