/**
 * ACM PSU — Club Records Workbook Setup
 *
 * PURPOSE
 * -------
 * Prepares and formats the administrative Google Sheets workbook used by the
 * ACM PSU platform.
 *
 * Supabase remains the canonical system of record for the platform.
 *
 * This script:
 * - creates missing workbook tabs;
 * - applies headers and formatting;
 * - protects externally managed event-registration tabs from accidental edits;
 * - never reads data from Supabase;
 * - never accepts public registration submissions;
 * - never clears registration rows.
 *
 * TWO DIFFERENT GROUPS OF TABS
 * ----------------------------
 *
 * CANONICAL_SHEETS
 *   Supabase-owned snapshot mirrors.
 *
 *   These worksheets are refreshed by the `club-records-sheet-sync`
 *   Supabase Edge Function. Supabase is authoritative and the worksheets are
 *   administrative copies of platform data.
 *
 * EVENT_SHEETS
 *   Externally managed event-registration worksheets.
 *
 *   Current event tabs:
 *   - jam26
 *   - ctf30
 *
 *   They are populated by the event registration integrations and are
 *   deliberately excluded from the normal Supabase snapshot sync.
 *
 *   This setup script never rewrites an existing event header or registration
 *   data. It may seed row 1 only when an event worksheet is empty.
 */


/* ==========================================================================
   CONFIGURATION
   ========================================================================== */


/**
 * Supabase-owned workbook mirrors.
 *
 * These headers should match the current output of the ACM PSU platform's
 * Google Sheets synchronization system.
 */
var CANONICAL_SHEETS = {
  'People': [
    'Name',
    'PSU Email',
    'Person Type',
    'University Role',
    'ACM Role',
    'Project Roles',
    'Account State',
    'Admin/System Roles',
    'Student ID',
    'Major',
    'Academic Year',
    'Membership Status'
  ],

  'Members': [
    'Name',
    'PSU Email',
    'Student ID',
    'Major',
    'Academic Year',
    'Membership Status',
    'Membership Start',
    'Membership End',
    'Member Number',
    'Chapter Year',
    'Club Position',
    'Account State'
  ],

  'Club Positions': [
    'Position ID',
    'Slug',
    'Position Name',
    'Category',
    'Rank',
    'Active',
    'Holder Name',
    'Holder Email',
    'University Role',
    'Assignment Start',
    'Assignment End',
    'Chapter Year',
    'Assignment Status'
  ],

  'Opportunity Positions': [
    'Opportunity ID',
    'Project',
    'Project Kind',
    'Project Status',
    'Position',
    'Description',
    'Openings',
    'Approved',
    'Pending',
    'Remaining',
    'Open',
    'Closes On',
    'Created At'
  ],

  'Position Applications': [
    'Application ID',
    'Applicant Name',
    'Email',
    'University Role',
    'Project',
    'Position',
    'Availability',
    'Note',
    'Status',
    'Admin Note',
    'Decided By',
    'Decided At',
    'Applied At'
  ],

  'Event Participation': [
    'Participation ID',
    'Person Name',
    'Email',
    'University Role',
    'Project',
    'Project Kind',
    'Opportunity Position',
    'Role',
    'Status',
    'Started',
    'Ended',
    'Verified At',
    'Verified By',
    'Updated At'
  ],

  'Contributions': [
    'Contribution ID',
    'Person Name',
    'Email',
    'University Role',
    'Project',
    'Title',
    'Type',
    'Role',
    'Description',
    'Occurred On',
    'Status',
    'Verified At',
    'Reviewed By',
    'Review Note',
    'Created At'
  ],

  'Inquiries': [
    'Reference',
    'Received',
    'From',
    'Email',
    'Category',
    'Subject',
    'Message',
    'Status',
    'Assigned To',
    'Responded At',
    'Response Delivered',
    'Closed At'
  ],

  'University Export Log': [
    'Generated At',
    'Dataset',
    'Format',
    'Rows',
    'Generated By',
    'Destination'
  ]
};


/**
 * Event-registration worksheets.
 *
 * IMPORTANT
 * ---------
 * These tabs are NOT Supabase snapshot mirrors.
 *
 * Existing event headers are treated as externally owned. If the configured
 * headers below differ from the live worksheet, this script reports the
 * mismatch and changes nothing.
 *
 * Row shape:
 *
 * jam26
 *   One row per TEAM SUBMISSION.
 *
 *   The personal fields identify the participant submitting the registration.
 *   Team Name and Team Members describe the registered team.
 *
 * ctf30
 *   One row per TEAM.
 *
 *   The captain has the primary contact phone number.
 *   Members 2 and 3 have:
 *   - Name
 *   - University ID
 *   - University Email
 *   - Major
 */
var EVENT_SHEETS = {
  // ACM Programming Jam 2026 — one row per team submission.
  'jam26': [
    'Timestamp',
    'Full Name',
    'University ID',
    'University Email',
    'Phone Number',
    'Major',
    'Team Name',
    'Team Members'
  ],

  // ACM/CyberTech CTF 3.0 — one row per team.
  'ctf30': [
    'Timestamp',
    'Team Name',

    'Captain Name',
    'Captain University ID',
    'Captain University Email',
    'Captain Phone Number',
    'Captain Major',

    'Member 2 Name',
    'Member 2 University ID',
    'Member 2 University Email',
    'Member 2 Major',

    'Member 3 Name',
    'Member 3 University ID',
    'Member 3 University Email',
    'Member 3 Major',

    'Experience Level'
  ]
};


var HEADER_BACKGROUND = '#142033';
var EVENT_HEADER_BACKGROUND = '#1d3a2f';
var HEADER_FONT_COLOR = '#ffffff';


/* ==========================================================================
   MAIN SETUP
   ========================================================================== */


/**
 * Main workbook setup function.
 *
 * Run this from:
 *
 * ACM Records → Prepare workbook tabs
 *
 * or manually from the Apps Script editor.
 */
function setupClubRecordsWorkbook() {
  var book = SpreadsheetApp.getActiveSpreadsheet();

  if (!book) {
    throw new Error(
      'Open this script from the ACM PSU — Club Records workbook.'
    );
  }

  /*
   * Fail before touching anything if a worksheet has accidentally been placed
   * in both configuration groups.
   */
  assertNoSheetGroupOverlap_();

  var notes = [];

  /*
   * Prepare Supabase-owned mirror tabs.
   */
  Object.keys(CANONICAL_SHEETS).forEach(function (name) {
    prepareCanonicalSheet_(
      book,
      name,
      CANONICAL_SHEETS[name],
      notes
    );
  });

  /*
   * Prepare externally managed event-registration tabs.
   */
  Object.keys(EVENT_SHEETS).forEach(function (name) {
    prepareEventSheet_(
      book,
      name,
      EVENT_SHEETS[name],
      notes
    );
  });

  SpreadsheetApp.flush();

  report_(notes);
}


/* ==========================================================================
   SAFETY GUARDS
   ========================================================================== */


/**
 * Event-registration tabs must never become Supabase mirror tabs.
 *
 * If an event worksheet were accidentally added to CANONICAL_SHEETS, the
 * normal Supabase workbook synchronization could clear and rebuild it.
 *
 * Stop immediately instead.
 */
function assertNoSheetGroupOverlap_() {
  Object.keys(EVENT_SHEETS).forEach(function (name) {
    if (CANONICAL_SHEETS.hasOwnProperty(name)) {
      throw new Error(
        'Configuration error: "' +
          name +
          '" is listed in both CANONICAL_SHEETS and EVENT_SHEETS. ' +
          'Event-registration tabs must never be targeted by the normal ' +
          'Supabase snapshot synchronization.'
      );
    }
  });
}


/* ==========================================================================
   CANONICAL SUPABASE MIRROR TABS
   ========================================================================== */


/**
 * Prepares a Supabase-owned mirror worksheet.
 *
 * Row 1 is controlled by the current platform schema.
 *
 * This setup function does NOT clear existing data rows. The actual Edge
 * Function remains responsible for refreshing snapshot data.
 */
function prepareCanonicalSheet_(book, name, headers, notes) {
  var sheet = book.getSheetByName(name);

  if (!sheet) {
    sheet = book.insertSheet(name);
  }

  ensureEnoughColumns_(sheet, headers.length);

  sheet
    .getRange(1, 1, 1, headers.length)
    .setValues([headers]);

  styleHeader_(
    sheet,
    headers.length,
    HEADER_BACKGROUND
  );

  formatColumns_(sheet, headers);

  applyFilter_(
    sheet,
    headers.length
  );

  notes.push(
    'Mirror  ' +
      name +
      ' — headers applied (' +
      headers.length +
      ' columns).'
  );
}


/* ==========================================================================
   EVENT REGISTRATION TABS
   ========================================================================== */


/**
 * Prepares an externally managed event-registration worksheet.
 *
 * SAFE BEHAVIOR
 * -------------
 *
 * Missing tab:
 *   Creates it and seeds configured headers.
 *
 * Existing but empty tab:
 *   Seeds configured headers.
 *
 * Existing tab with matching headers:
 *   Leaves row 1 untouched.
 *
 * Existing tab with DIFFERENT headers:
 *   Writes nothing and reports a HEADER MISMATCH.
 *
 * Registration rows are never cleared or rewritten here.
 */
function prepareEventSheet_(book, name, headers, notes) {
  var configured =
    headers && headers.length
      ? headers
      : null;

  var sheet = book.getSheetByName(name);
  var created = false;

  if (!sheet) {
    sheet = book.insertSheet(name);
    created = true;
  }

  var existing = readHeaderRow_(sheet);

  /*
   * Empty worksheet + configured schema:
   * safe to seed row 1.
   */
  if (configured && !existing.length) {
    ensureEnoughColumns_(
      sheet,
      configured.length
    );

    sheet
      .getRange(
        1,
        1,
        1,
        configured.length
      )
      .setValues([configured]);

    existing = configured.slice();

    notes.push(
      'Event   ' +
        name +
        ' — ' +
        (created ? 'created' : 'was empty') +
        ', header row seeded (' +
        configured.length +
        ' columns).'
    );
  }

  /*
   * Existing worksheet disagrees with configuration:
   * live worksheet wins.
   */
  else if (
    configured &&
    !sameHeaders_(configured, existing)
  ) {
    notes.push(
      'Event   ' +
        name +
        ' — HEADER MISMATCH, nothing written.\n' +
        '          in sheet: ' +
        existing.join(' | ') +
        '\n' +
        '          in script: ' +
        configured.join(' | ') +
        '\n' +
        '          Update EVENT_SHEETS in Code.gs to match the live sheet.'
    );
  }

  /*
   * Correct existing event header.
   */
  else if (configured) {
    notes.push(
      'Event   ' +
        name +
        ' — header row matches, left untouched.'
    );
  }

  /*
   * No configured schema but an existing header exists.
   */
  else if (existing.length) {
    notes.push(
      'Event   ' +
        name +
        ' — no header configured; existing row 1 left untouched.'
    );
  }

  /*
   * Brand-new empty tab with no configured schema.
   */
  else {
    notes.push(
      'Event   ' +
        name +
        ' — ' +
        (created ? 'created, ' : '') +
        'empty and no header configured.'
    );
  }

  /*
   * Styling is allowed because it does not change registration values.
   */
  var width =
    existing.length ||
    sheet.getLastColumn();

  if (width > 0) {
    styleHeader_(
      sheet,
      width,
      EVENT_HEADER_BACKGROUND
    );

    applyFilter_(
      sheet,
      width
    );

    formatColumns_(
      sheet,
      existing.length
        ? existing
        : headers
    );
  }

  /*
   * Warn humans before editing an event-registration worksheet.
   *
   * This is intentionally warning-only, not a hard lock.
   */
  protectEventSheet_(
    sheet,
    name
  );
}


/* ==========================================================================
   EVENT SHEET PROTECTION
   ========================================================================== */


/**
 * Applies warning-only protection to an event-registration worksheet.
 *
 * Why warning-only?
 *
 * It warns a human editing through Google Sheets while still allowing
 * programmatic integrations to write.
 *
 * The registration writer identity is intentionally not assumed here.
 */
function protectEventSheet_(sheet, name) {
  var description =
    'ACM event registrations (' +
    name +
    ') — externally managed. ' +
    'Excluded from the Supabase snapshot sync. ' +
    'Do not sort, clear, or paste over registration data.';

  var protections =
    sheet.getProtections(
      SpreadsheetApp.ProtectionType.SHEET
    );

  var protection;

  if (protections && protections.length) {
    protection = protections[0];
  } else {
    protection = sheet.protect();
  }

  protection.setDescription(description);
  protection.setWarningOnly(true);
}


/* ==========================================================================
   HEADER UTILITIES
   ========================================================================== */


/**
 * Reads row 1 as a normalized list of header names.
 */
function readHeaderRow_(sheet) {
  var width = sheet.getLastColumn();

  if (
    width < 1 ||
    sheet.getLastRow() < 1
  ) {
    return [];
  }

  var row = sheet
    .getRange(
      1,
      1,
      1,
      width
    )
    .getValues()[0];

  /*
   * Remove trailing blank header cells without collapsing valid columns in
   * the middle of a header row.
   */
  while (
    row.length &&
    String(row[row.length - 1]).trim() === ''
  ) {
    row.pop();
  }

  return row.map(function (cell) {
    return String(cell).trim();
  });
}


/**
 * Exact normalized header comparison.
 */
function sameHeaders_(a, b) {
  if (a.length !== b.length) {
    return false;
  }

  for (
    var i = 0;
    i < a.length;
    i += 1
  ) {
    if (
      String(a[i]).trim() !==
      String(b[i]).trim()
    ) {
      return false;
    }
  }

  return true;
}


/* ==========================================================================
   FORMATTING
   ========================================================================== */


/**
 * Ensures enough worksheet columns exist.
 */
function ensureEnoughColumns_(sheet, requiredColumns) {
  var currentColumns =
    sheet.getMaxColumns();

  if (
    currentColumns <
    requiredColumns
  ) {
    sheet.insertColumnsAfter(
      currentColumns,
      requiredColumns -
        currentColumns
    );
  }
}


/**
 * Applies the standard header appearance.
 */
function styleHeader_(sheet, width, background) {
  if (width < 1) {
    return;
  }

  sheet.setFrozenRows(1);

  sheet
    .getRange(
      1,
      1,
      1,
      width
    )
    .setBackground(background)
    .setFontColor(
      HEADER_FONT_COLOR
    )
    .setFontWeight('bold')
    .setHorizontalAlignment('center')
    .setVerticalAlignment('middle')
    .setWrap(true);

  sheet.setRowHeight(
    1,
    42
  );
}


/**
 * Applies column sizing and data formatting.
 */
function formatColumns_(sheet, headers) {
  if (
    !headers ||
    !headers.length
  ) {
    return;
  }

  var maxRows =
    sheet.getMaxRows();

  headers.forEach(
    function (header, index) {
      var column =
        index + 1;

      sheet.setColumnWidth(
        column,
        columnWidthFor_(header)
      );

      /*
       * Do not needlessly format an empty worksheet below row 1.
       */
      if (maxRows <= 1) {
        return;
      }

      var dataRange =
        sheet.getRange(
          2,
          column,
          maxRows - 1,
          1
        );

      dataRange
        .setVerticalAlignment(
          'middle'
        );

      if (
        isLongTextColumn_(header)
      ) {
        dataRange
          .setWrap(true)
          .setVerticalAlignment(
            'top'
          );
      } else {
        dataRange.setWrap(false);
      }

      if (
        isDateTimeColumn_(header)
      ) {
        dataRange.setNumberFormat(
          'yyyy-mm-dd hh:mm'
        );
      }

      if (
        isDateOnlyColumn_(header)
      ) {
        dataRange.setNumberFormat(
          'yyyy-mm-dd'
        );
      }
    }
  );
}


/**
 * Recreates a basic filter for the visible table.
 */
function applyFilter_(sheet, width) {
  if (width < 1) {
    return;
  }

  var existingFilter =
    sheet.getFilter();

  if (existingFilter) {
    existingFilter.remove();
  }

  /*
   * Only create the filter when there is at least one actual data row.
   *
   * Header-only filters can conflict with an existing Google Sheets table or
   * overlapping filter range. The frozen/styled header remains enough until
   * data exists.
   */
  if (sheet.getLastRow() <= 1) {
    return;
  }

  sheet
    .getRange(
      1,
      1,
      sheet.getLastRow(),
      width
    )
    .createFilter();
}


/**
 * Appropriate display width for a column.
 */
function columnWidthFor_(header) {
  var text =
    String(header || '');

  if (
    text.includes('Message') ||
    text.includes('Response') ||
    text.includes('Contribution') ||
    text.includes('Description') ||
    text.includes('Admin Note') ||
    text.includes('Review Note') ||
    text === 'Note' ||
    text === 'Team Members'
  ) {
    return 320;
  }

  if (
    text.includes('Email') ||
    text.includes('Project') ||
    text.includes('Event')
  ) {
    return 230;
  }

  if (
    text.includes('Name') ||
    text.includes('Current Holder')
  ) {
    return 210;
  }

  if (
    text.includes('Availability')
  ) {
    return 220;
  }

  if (
    isDateTimeColumn_(text) ||
    isDateOnlyColumn_(text)
  ) {
    return 175;
  }

  if (
    text.includes('ID')
  ) {
    return 190;
  }

  if (
    text.includes('Status')
  ) {
    return 160;
  }

  if (
    text.includes('Major')
  ) {
    return 190;
  }

  if (
    text.includes('Phone')
  ) {
    return 170;
  }

  return 150;
}


/**
 * Long-text fields should wrap.
 */
function isLongTextColumn_(header) {
  var text =
    String(header || '');

  return (
    text.includes('Message') ||
    text.includes('Response') ||
    text.includes('Contribution') ||
    text.includes('Description') ||
    text.includes('Availability') ||
    text.includes('Admin Note') ||
    text.includes('Review Note') ||
    text === 'Note' ||
    text === 'Team Members'
  );
}


/**
 * Timestamp/date-time fields.
 */
function isDateTimeColumn_(header) {
  var text =
    String(header || '');

  return (
    text === 'Timestamp' ||
    text === 'Received' ||
    text === 'Generated At' ||
    text === 'Created At' ||
    text === 'Updated At' ||
    text === 'Applied At' ||
    text === 'Decided At' ||
    text === 'Verified At' ||
    text === 'Responded At' ||
    text === 'Closed At' ||
    text.endsWith(' At')
  );
}


/**
 * Date-only fields.
 */
function isDateOnlyColumn_(header) {
  var text =
    String(header || '');

  return (
    text === 'Membership Start' ||
    text === 'Membership End' ||
    text === 'Assignment Start' ||
    text === 'Assignment End' ||
    text === 'Started' ||
    text === 'Ended' ||
    text === 'Occurred On' ||
    text === 'Closes On'
  );
}


/* ==========================================================================
   REPORTING
   ========================================================================== */


/**
 * Displays the setup report.
 *
 * Works when called from the spreadsheet UI or directly from the Apps Script
 * editor.
 */
function report_(notes) {
  var message =
    notes.join('\n') +
    '\n\n' +
    'Canonical mirror tabs are refreshed from Supabase through the ACM ' +
    'platform Google Sheet synchronization. Event-registration tabs are ' +
    'externally managed and are excluded from that snapshot sync.';

  Logger.log(message);

  try {
    SpreadsheetApp
      .getUi()
      .alert(message);
  } catch (err) {
    /*
     * No spreadsheet UI is available when execution is initiated in certain
     * trigger/editor contexts. Logger output above remains available.
     */
  }
}


/* ==========================================================================
   WORKBOOK MENU
   ========================================================================== */


/**
 * Adds the workbook maintenance menu whenever the spreadsheet is opened.
 */
function onOpen() {
  try {
    SpreadsheetApp
      .getUi()
      .createMenu('ACM Records')
      .addItem(
        'Prepare workbook tabs',
        'setupClubRecordsWorkbook'
      )
      .addToUi();
  } catch (err) {
    /*
     * Container UI unavailable.
     * setupClubRecordsWorkbook() remains runnable manually.
     */
  }
}


/* ==========================================================================
   PUBLIC EVENT REGISTRATION ENDPOINT

   Accepts registrations from the two live event sites and appends them to the
   externally managed event tabs. This is the ONLY public write path in this
   script, and it can reach exactly two worksheets: jam26 and ctf30.

   Contract (verified against the live front-ends, do not change unilaterally):

     transport   application/x-www-form-urlencoded, posted by a hidden-iframe
                 form. Read from e.parameter. No JSON, no CORS.
     routing     ctf30 sends event=ctf30. JAM.26 sends no event field, so an
                 absent/unknown value routes to jam26.
     reply       an HtmlService page calling parent.postMessage({source,message}).
     source      MUST differ per event, because each form filters on its own tag:
                   jam26 -> 'jam26'                  (team-formation.html)
                   ctf30 -> 'acm-event-registration' (register.html)
                 Returning the wrong tag makes that form hang for 20s.
     success     message === 'OK'. Failures are 'Error: <reason>'.

   Canonical Supabase mirror tabs are unreachable from here: REGISTRATION_EVENTS
   is a closed allowlist and the sheet name never comes from the request.
   ========================================================================== */


/**
 * The only worksheets a public request may ever reach. The `sheet` value is a
 * constant in this file; nothing from the payload selects a worksheet.
 */
var REGISTRATION_EVENTS = {
  jam26: {
    sheet: 'jam26',
    replySource: 'jam26',
    fields: {
      fullName:        'Full Name',
      universityId:    'University ID',
      universityEmail: 'University Email',
      phoneNumber:     'Phone Number',
      major:           'Major',
      teamName:        'Team Name',
      teamMembers:     'Team Members'
    },
    required: ['fullName', 'universityId', 'universityEmail', 'phoneNumber', 'major', 'teamName'],
    emailFields: ['universityEmail'],
    optionalGroup: [],
    enums: {},
    limits: {
      fullName: 120, universityId: 40, universityEmail: 254, phoneNumber: 40,
      major: 120, teamName: 120, teamMembers: 1500
    },
    // Each entry: sheet columns scanned against the submitted values.
    uniqueChecks: [
      { headers: ['University Email'], fields: ['universityEmail'],
        message: 'this participant is already registered' },
      { headers: ['University ID'], fields: ['universityId'],
        message: 'this participant is already registered' }
    ],
    rateFields: ['universityEmail', 'universityId']
  },

  ctf30: {
    sheet: 'ctf30',
    replySource: 'acm-event-registration',
    fields: {
      teamName:      'Team Name',
      captainName:   'Captain Name',
      captainId:     'Captain University ID',
      captainEmail:  'Captain University Email',
      captainPhone:  'Captain Phone Number',
      captainMajor:  'Captain Major',
      member2Name:   'Member 2 Name',
      member2Id:     'Member 2 University ID',
      member2Email:  'Member 2 University Email',
      member2Major:  'Member 2 Major',
      member3Name:   'Member 3 Name',
      member3Id:     'Member 3 University ID',
      member3Email:  'Member 3 University Email',
      member3Major:  'Member 3 Major',
      experience:    'Experience Level'
    },
    required: [
      'teamName', 'experience',
      'captainName', 'captainId', 'captainEmail', 'captainPhone', 'captainMajor',
      'member2Name', 'member2Id', 'member2Email', 'member2Major'
    ],
    emailFields: ['captainEmail', 'member2Email'],
    // All four or none, so a half-filled third member never lands.
    optionalGroup: ['member3Name', 'member3Id', 'member3Email', 'member3Major'],
    optionalGroupEmails: ['member3Email'],
    enums: { experience: ['Beginner', 'Intermediate', 'Advanced'] },
    limits: {
      teamName: 120, experience: 40,
      captainName: 120, captainId: 40, captainEmail: 254, captainPhone: 40, captainMajor: 120,
      member2Name: 120, member2Id: 40, member2Email: 254, member2Major: 120,
      member3Name: 120, member3Id: 40, member3Email: 254, member3Major: 120
    },
    uniqueChecks: [
      { headers: ['Captain University Email', 'Member 2 University Email', 'Member 3 University Email'],
        fields: ['captainEmail', 'member2Email', 'member3Email'],
        message: 'one of these participants is already registered' },
      { headers: ['Captain University ID', 'Member 2 University ID', 'Member 3 University ID'],
        fields: ['captainId', 'member2Id', 'member3Id'],
        message: 'one of these participants is already registered' },
      { headers: ['Team Name'], fields: ['teamName'],
        message: 'that team name is already taken' }
    ],
    // Nobody may occupy two slots on the same team.
    distinctWithinRow: [
      { fields: ['captainEmail', 'member2Email', 'member3Email'],
        message: 'each member needs a different university email' },
      { fields: ['captainId', 'member2Id', 'member3Id'],
        message: 'each member needs a different university ID' }
    ],
    rateFields: ['captainEmail', 'teamName']
  }
};

/** Same window both front-ends wait on before giving up, less a safety margin. */
var REGISTRATION_LOCK_MS = 15000;
/** Seconds an identical submitter is asked to wait before retrying. */
var REGISTRATION_RATE_SECONDS = 300;
var DEFAULT_FIELD_LIMIT = 500;


/**
 * Public registration intake. Append-only, allowlisted, and never able to read
 * back or modify existing rows.
 */
function doPost(e) {
  var lock = LockService.getScriptLock();
  var config = null;
  try {
    lock.waitLock(REGISTRATION_LOCK_MS);

    var form = (e && e.parameter) || {};
    var requested = String(form.event || '').trim();
    var key = REGISTRATION_EVENTS.hasOwnProperty(requested) ? requested : 'jam26';
    config = REGISTRATION_EVENTS[key];

    // An explicit but unknown event is refused rather than silently filed as a
    // JAM.26 registration. An absent event is JAM.26 by contract.
    if (requested && !REGISTRATION_EVENTS.hasOwnProperty(requested)) {
      return registrationReply(REGISTRATION_EVENTS.jam26.replySource, 'Error: unknown event');
    }

    return handleEventRegistration(config, form);
  } catch (err) {
    // Detail goes to the execution log for organizers; the browser sees nothing
    // about the workbook, the failure site, or the stack.
    console.error(err);
    var source = config ? config.replySource : REGISTRATION_EVENTS.jam26.replySource;
    return registrationReply(source, 'Error: something went wrong on our side. Please try again, or contact the organizers.');
  } finally {
    try { lock.releaseLock(); } catch (releaseError) { /* lock was never taken */ }
  }
}


function handleEventRegistration(config, form) {
  var reply = function (message) { return registrationReply(config.replySource, message); };
  var value = function (field) { return String(form[field] === undefined ? '' : form[field]).trim(); };

  // Honeypot: report success so a bot learns nothing, and write no row.
  if (value('website')) return reply('OK');

  var i;

  for (i = 0; i < config.required.length; i += 1) {
    if (!value(config.required[i])) return reply('Error: missing ' + config.required[i]);
  }

  // Optional block is all-or-nothing.
  var group = config.optionalGroup || [];
  var filled = group.filter(function (field) { return value(field); });
  var hasGroup = group.length > 0 && filled.length === group.length;
  if (filled.length && !hasGroup) {
    return reply('Error: complete every optional member field or leave them all blank');
  }

  var fieldNames = Object.keys(config.fields);
  for (i = 0; i < fieldNames.length; i += 1) {
    var field = fieldNames[i];
    var limit = config.limits[field] || DEFAULT_FIELD_LIMIT;
    if (value(field).length > limit) return reply('Error: ' + field + ' is too long');
  }

  var enumFields = Object.keys(config.enums || {});
  for (i = 0; i < enumFields.length; i += 1) {
    if (config.enums[enumFields[i]].indexOf(value(enumFields[i])) === -1) {
      return reply('Error: invalid ' + enumFields[i]);
    }
  }

  var emailFields = (config.emailFields || []).slice();
  if (hasGroup) emailFields = emailFields.concat(config.optionalGroupEmails || []);
  for (i = 0; i < emailFields.length; i += 1) {
    if (!isRegistrationEmail(value(emailFields[i]))) {
      return reply('Error: invalid ' + emailFields[i]);
    }
  }

  var withinRow = config.distinctWithinRow || [];
  for (i = 0; i < withinRow.length; i += 1) {
    var seen = withinRow[i].fields
      .map(function (f) { return value(f).toLowerCase(); })
      .filter(function (v) { return v; });
    if (hasArrayDuplicate(seen)) return reply('Error: ' + withinRow[i].message);
  }

  // Resolve the worksheet from the constant config, never from the payload.
  var sheet = registrationSheet_(config.sheet);
  if (!sheet) return reply('Error: registration storage is not ready. Please contact the organizers.');

  var headers = readHeaderRow_(sheet);

  // Preserve the header-mismatch safety rule: if the tab is not laid out as
  // expected, refuse rather than write a row with silently dropped columns.
  var missing = missingRegistrationHeaders(config, headers);
  if (missing.length) {
    console.error('Sheet ' + config.sheet + ' is missing columns: ' + missing.join(', '));
    return reply('Error: registration storage is not ready. Please contact the organizers.');
  }

  var duplicate = findExistingRegistration(sheet, headers, config, value);
  if (duplicate) return reply('Error: ' + duplicate);

  // Rate limit last, so a rejected attempt never locks out an immediate retry.
  var identity = (config.rateFields || [])
    .map(function (f) { return value(f).toLowerCase(); })
    .join('|');
  if (identity && !allowRegistrationRequest(config.sheet, identity, REGISTRATION_RATE_SECONDS)) {
    return reply('Error: please wait before submitting again');
  }

  var row = new Array(headers.length);
  for (i = 0; i < row.length; i += 1) row[i] = '';

  fieldNames.forEach(function (name) {
    var col = headers.indexOf(config.fields[name]);
    if (col !== -1) row[col] = safeRegistrationCell(value(name));
  });

  var tsCol = headers.indexOf('Timestamp');
  if (tsCol !== -1) row[tsCol] = new Date();

  // appendRow only ever adds a new last row. No existing registration is read
  // back to the caller, cleared, or overwritten anywhere in this handler.
  sheet.appendRow(row);
  return reply('OK');
}


/**
 * This script is bound to the Club Records workbook, so the active spreadsheet
 * is the right target. openById is a fallback for execution contexts where the
 * binding is unavailable; the id is a document identifier, not a credential.
 */
function registrationSheet_(name) {
  if (!REGISTRATION_EVENTS.hasOwnProperty(name)) return null;  // defence in depth
  var book = SpreadsheetApp.getActive();
  if (!book && typeof REGISTRATION_SPREADSHEET_ID !== 'undefined' && REGISTRATION_SPREADSHEET_ID) {
    book = SpreadsheetApp.openById(REGISTRATION_SPREADSHEET_ID);
  }
  if (!book) return null;
  return book.getSheetByName(name);
}


function missingRegistrationHeaders(config, headers) {
  var expected = ['Timestamp'];
  Object.keys(config.fields).forEach(function (field) { expected.push(config.fields[field]); });
  return expected.filter(function (header) { return headers.indexOf(header) === -1; });
}


/**
 * One read of the data range, then every uniqueness rule is answered from it.
 * Returns the message for the first rule that matches, or '' when the
 * submission is new. Nothing read here is ever returned to the caller.
 */
function findExistingRegistration(sheet, headers, config, value) {
  var checks = config.uniqueChecks || [];
  if (!checks.length || sheet.getLastRow() < 2) return '';

  var rows = sheet.getRange(2, 1, sheet.getLastRow() - 1, headers.length).getDisplayValues();

  for (var c = 0; c < checks.length; c += 1) {
    var check = checks[c];
    var wanted = {};
    var any = false;
    check.fields.forEach(function (field) {
      var v = value(field).toLowerCase();
      if (v) { wanted[v] = true; any = true; }
    });
    if (!any) continue;

    for (var h = 0; h < check.headers.length; h += 1) {
      var col = headers.indexOf(check.headers[h]);
      if (col === -1) continue;
      for (var r = 0; r < rows.length; r += 1) {
        var cell = String(rows[r][col] === undefined ? '' : rows[r][col]).trim().toLowerCase();
        if (cell && wanted[cell]) return check.message;
      }
    }
  }
  return '';
}


function hasArrayDuplicate(values) {
  for (var i = 0; i < values.length; i += 1) {
    if (values.indexOf(values[i]) !== i) return true;
  }
  return false;
}


function isRegistrationEmail(value) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(value || '').trim());
}


/**
 * Neutralises spreadsheet formula injection. A leading =, +, - or @ makes
 * Sheets evaluate the cell, so the value is stored as literal text instead.
 */
function safeRegistrationCell(value) {
  var text = String(value || '').trim();
  return /^[=+\-@]/.test(text) ? "'" + text : text;
}


/**
 * Per-identity throttle held in the script cache. Keys are hashed so no email
 * address or university ID is stored in the cache in readable form.
 */
function allowRegistrationRequest(scope, identity, seconds) {
  var digest = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, scope + '|' + identity);
  var key = Utilities.base64EncodeWebSafe(digest).slice(0, 80);
  var cache = CacheService.getScriptCache();
  if (cache.get(key)) return false;
  cache.put(key, '1', seconds);
  return true;
}


/**
 * The reply both front-ends listen for. `source` must match the tag that the
 * requesting form filters on, or that form ignores this message and times out.
 */
function registrationReply(source, message) {
  var payload = JSON.stringify({ source: String(source), message: String(message) })
    .replace(/</g, '\\u003c');
  return HtmlService.createHtmlOutput(
    '<p>' + escapeRegistrationHtml(String(message)) + '</p>' +
    '<script>parent.postMessage(' + payload + ', "*");<\/script>'
  );
}


function escapeRegistrationHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}


/**
 * GET is not a registration path and reports nothing about the workbook.
 */
function doGet() {
  return json_({ status: 'ok', message: 'ACM PSU event registration endpoint is live.' });
}


/** JSON response helper. */
function json_(payload) {
  return ContentService
    .createTextOutput(JSON.stringify(payload))
    .setMimeType(ContentService.MimeType.JSON);
}
